#include <stdio.h>

int main()
{
    char *str = "AGRO3.SA,RAIL3.SA,ALPA3.SA,AMAR3.SA,ABEV3.SA,ADHM3.SA,BBAS3.SA,BBDC3.SA,BEEF3.SA,BPHA3.SA,BRAP3.SA,BRFS3.SA,BRKM3.SA,BRPR3.SA,OIBR3.SA,B3SA3.SA,CCRO3.SA,CEED3.SA,CMIG3.SA,CPFE3.SA,CPLE3.SA,CSAN3.SA,CSMG3.SA,CSNA3.SA,CYRE3.SA,DASA3.SA,DIRR3.SA,ECOR3.SA,ELET3.SA,EMBR3.SA,EQTL3.SA,YDUQ3.SA,ETER3.SA,EVEN3.SA,EZTC3.SA,FHER3.SA,FLRY3.SA,FRIO3.SA,GFSA3.SA,GGBR3.SA,GOAU3.SA,GRND3.SA,GSHP3.SA,HBOR3.SA,PRIO3.SA,HYPE3.SA,MEAL3.SA,INEP3.SA,ITSA3.SA,ITUB3.SA,JBSS3.SA,JFEN3.SA,JHSF3.SA,JSLG3.SA,KEPL3.SA,LEVE3.SA,LIGT3.SA,LOGN3.SA,LPSB3.SA,LREN3.SA,LUPA3.SA,MDIA3.SA,MGLU3.SA,MILS3.SA,ENEV3.SA,MRFG3.SA,MRVE3.SA,MULT3.SA,MYPK3.SA,ODPV3.SA,OSXB3.SA,PDGR3.SA,PETR3.SA,PFRM3.SA,PLAS3.SA,PMAM3.SA,POMO3.SA,POSI3.SA,PSSA3.SA,PTBL3.SA,QUAL3.SA,RAPT3.SA,RDNI3.SA,RENT3.SA,ROMI3.SA,RSID3.SA,SBSP3.SA,SCAR3.SA,SGPS3.SA,SHOW3.SA,SLCE3.SA,SMTO3.SA,EGIE3.SA,TCSA3.SA,TECN3.SA,TGMA3.SA,TOTS3.SA,TPIS3.SA,TRIS3.SA,UGPA3.SA,UNIP3.SA,USIM3.SA,VALE3.SA,VIVR3.SA,VIVT3.SA,VLID3.SA,WEGE3.SA,STBP3.SA,CGRA3.SA,COCE3.SA,TASA3.SA,COGN3.SA,RADL3.SA,UCAS3.SA,ANIM3.SA,BBSE3.SA,CVCB3.SA,SEER3.SA,TUPY3.SA,BIOM3.SA,NUTR3.SA,BAZA3.SA,SANB3.SA,FRAS3.SA,OFSA3.SA,GUAR3.SA,WHRL3.SA,RPMG3.SA,BRSR3.SA,BEES3.SA,BMEB3.SA,BMIN3.SA,BMKS3.SA,BNBR3.SA,BRIV3.SA,CBEE3.SA,CEEB3.SA,CGAS3.SA,CRIV3.SA,CTNM3.SA,CTSA3.SA,DTCY3.SA,ENGI3.SA,ENMT3.SA,FESA3.SA,JOPA3.SA,KLBN3.SA,MNDL3.SA,MNPR3.SA,PNVL3.SA,RANI3.SA,RCSL3.SA,REDE3.SA,WLMM3.SA,SLED3.SA,TELB3.SA,VULC3.SA,AALR3.SA,AFLT3.SA,BGIP3.SA,CEBR3.SA,CEDO3.SA,GPAR3.SA,MAPT3.SA,RPAD3.SA,VSPT3.SA,MOVI3.SA,RNEW3.SA,TEND3.SA,CRFB3.SA,IRBR3.SA,GEPA3.SA,SAPR3.SA,CAML3.SA,SUZB3.SA,NEOE3.SA,MSPA3.SA,HAPV3.SA,GPIV33.SA,ALUP3.SA,LOGG3.SA,TAEE3.SA,AZEV3.SA,AHEB3.SA,BALM3.SA,BPAC3.SA,EALT3.SA,ECPR3.SA,HAGA3.SA,LIPR3.SA,PATI3.SA,PEAB3.SA,VAMO3.SA,MOAR3.SA,VIVA3.SA,CEAB3.SA";
    int cont = 0;
    for (int i = 0; str[i] != '\0'; i++)
    {
        if (str[i] == ',')
            cont++;
    }
    cont++; // a o último não possui vírgula depois
    printf("A base possui %d ativos", cont);

    return 0;
}